### PR TITLE
Create main.bat

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Arin-Grigoras** [comment]
sure but why a batch file ?

**Comment by ghost** [comment]
to greet the user( BTW, i got this from flutter which i am learning).

**Comment by Arin-Grigoras** [comment]
to greet the user when what ? the compiler is used?

**Comment by Arin-Grigoras** [comment]
im sorry im very stupid

**Comment by ghost** [comment]
when they git clone

**Comment by Arin-Grigoras** [comment]
oh

**Comment by Arin-Grigoras** [comment]
didn't know that was a feature :)

**Pull request merged**
